# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Mon May  6 00:32:01 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 320)
        MainWindow.setMinimumSize(QtCore.QSize(380, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.selectRootButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectRootButton.sizePolicy().hasHeightForWidth())
        self.selectRootButton.setSizePolicy(sizePolicy)
        self.selectRootButton.setObjectName("selectRootButton")
        self.gridLayout.addWidget(self.selectRootButton, 0, 0, 1, 1)
        self.rootPathLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rootPathLabel.sizePolicy().hasHeightForWidth())
        self.rootPathLabel.setSizePolicy(sizePolicy)
        self.rootPathLabel.setObjectName("rootPathLabel")
        self.gridLayout.addWidget(self.rootPathLabel, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.contentTree = QtWidgets.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.contentTree.setFont(font)
        self.contentTree.setObjectName("contentTree")
        self.verticalLayout.addWidget(self.contentTree)
        self.bottomFunctionLayout = QtWidgets.QHBoxLayout()
        self.bottomFunctionLayout.setObjectName("bottomFunctionLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomFunctionLayout.addItem(spacerItem)
        self.constraintLayout = QtWidgets.QGridLayout()
        self.constraintLayout.setObjectName("constraintLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.constraintLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.constraintLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.sizeLimit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sizeLimit.setFont(font)
        self.sizeLimit.setObjectName("sizeLimit")
        self.constraintLayout.addWidget(self.sizeLimit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.constraintLayout.addWidget(self.label, 0, 0, 1, 1)
        self.timeLimit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeLimit.setFont(font)
        self.timeLimit.setObjectName("timeLimit")
        self.constraintLayout.addWidget(self.timeLimit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.constraintLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.bottomFunctionLayout.addLayout(self.constraintLayout)
        self.playRandomButton = QtWidgets.QPushButton(self.centralwidget)
        self.playRandomButton.setObjectName("playRandomButton")
        self.bottomFunctionLayout.addWidget(self.playRandomButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomFunctionLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.bottomFunctionLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Random Video Player", None, -1))
        self.selectRootButton.setText(QtWidgets.QApplication.translate("MainWindow", "Select Root Directory", None, -1))
        self.rootPathLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Please select a path", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "s", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Larger than:", None, -1))
        self.sizeLimit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "10", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Longer than:", None, -1))
        self.timeLimit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "MB", None, -1))
        self.playRandomButton.setText(QtWidgets.QApplication.translate("MainWindow", "Play Random", None, -1))

